-- Supabase 연결 테스트용 status_logs 테이블 생성
-- 1. Supabase SQL 에디터에서 실행한다.
-- 2. status_logs 테이블과 RLS 정책을 생성한다.
-- 3. 기본 샘플 데이터를 삽입한다.

create table if not exists status_logs (
  id uuid primary key default gen_random_uuid(),
  created_at timestamptz not null default timezone('utc', now()),
  message text not null,
  status text not null check (status in ('ok', 'warning', 'error'))
);

alter table status_logs enable row level security;

create policy "Allow anon read" on status_logs
  for select
  using (true);

insert into status_logs (message, status)
values
  ('Supabase 연결 테스트 완료', 'ok'),
  ('경고: 샘플 알림', 'warning');


-- 관리자 메뉴 테이블 생성 예시
create table if not exists admin_menus (
  menu_seq bigint generated by default as identity primary key,
  parent_menu_code varchar(50),
  menu_code varchar(50) not null unique,
  menu_name varchar(100) not null,
  menu_path text,
  sort_order int not null default 0,
  created_by varchar(50) not null,
  created_at timestamptz not null default timezone('utc', now()),
  updated_by varchar(50),
  updated_at timestamptz default timezone('utc', now()),
  icon_class varchar(50)
);

alter table admin_menus enable row level security;

create policy "Allow anon read admin menus"
  on admin_menus
  for select
  using (auth.role() = 'anon');

-- 관리자 메뉴 샘플 데이터
insert into admin_menus (parent_menu_code, menu_code, menu_name, menu_path, sort_order, created_by, icon_class)
values
  (null, 'dashboard', '대시보드', '/admin/dashboard', 1, 'system', 'bi-speedometer2'),
  (null, 'analytics', '통계', '/admin/sample', 2, 'system', 'bi-graph-up'),
  (null, 'components', '구성요소', null, 3, 'system', 'bi-puzzle'),
  ('components', 'components-buttons', '버튼', '/admin/sample', 1, 'system', 'bi-square'),
  ('components', 'components-forms', '입력폼', '/admin/sample', 2, 'system', 'bi-ui-checks');

-- 사용자 테이블 생성 예시
create table if not exists admin_users (
  user_seq bigint generated by default as identity,
  user_id varchar(50) primary key,
  password text not null,
  user_name varchar(100) not null,
  email varchar(150),
  role varchar(50),
  ip_address inet,
  login_status varchar(20),
  last_login_at timestamptz,
  created_by varchar(50),
  created_at timestamptz not null default timezone('utc', now()),
  updated_by varchar(50),
  updated_at timestamptz default timezone('utc', now())
);

alter table admin_users enable row level security;

create policy "Allow anon read admin users"
  on admin_users
  for select
  using (auth.role() = 'anon');

create table if not exists admin_user_history (
  history_id bigint generated by default as identity primary key,
  user_id varchar(50) not null,
  menu_code varchar(100) not null,
  action varchar(50) not null,
  action_detail text,
  result_status varchar(30),
  ip_address inet,
  user_agent text,
  request_id uuid,
  metadata jsonb,
  created_at timestamptz not null default timezone('utc', now())
);

alter table admin_user_history enable row level security;

create policy "Allow anon read admin user history"
  on admin_user_history
  for select
  using (auth.role() = 'anon');

-- 사용자 활동 이력 샘플 데이터
insert into admin_user_history (
  user_id, menu_code, action, action_detail, result_status, ip_address, user_agent, request_id, metadata, created_at
) values
  ('admin', 'dashboard', 'VIEW', '대시보드 진입', 'success', '192.168.0.10', 'Mozilla/5.0 (Windows NT 10.0; Win64; x64)', gen_random_uuid(), '{"notes": "첫 진입"}', timezone('utc', now()) - interval '5 minutes'),
  ('admin', 'user_manage', 'UPDATE', '사용자 권한 변경 (user01 -> manager)', 'success', '192.168.0.10', 'Mozilla/5.0 (Windows NT 10.0; Win64; x64)', gen_random_uuid(), '{"target_user": "user01"}', timezone('utc', now()) - interval '2 minutes'),
  ('manager01', 'reports', 'EXPORT', '월간 리포트 내려받기', 'success', '192.168.0.21', 'Mozilla/5.0 (Macintosh; Intel Mac OS X 13_3)', gen_random_uuid(), '{"format": "pdf"}', timezone('utc', now()) - interval '1 hour'),
  ('manager01', 'products', 'UPDATE', '상품 정보 수정 실패', 'error', '192.168.0.21', 'Mozilla/5.0 (Macintosh; Intel Mac OS X 13_3)', gen_random_uuid(), '{"error": "Validation error"}', timezone('utc', now()) - interval '50 minutes'),
  ('analyst02', 'analytics', 'VIEW', '트래픽 분석 대시보드 확인', 'success', '192.168.0.32', 'Mozilla/5.0 (X11; Linux x86_64)', gen_random_uuid(), null, timezone('utc', now()) - interval '10 minutes');
